---
# apt install
- when: nextcloud_client_apt_install | length > 0
  name: Apt install {{ nextcloud_client_apt_install }}
  become: true
  ansible.builtin.apt:
    state: present
    name: "{{ nextcloud_client_apt_install }}"

# apt remove
- when: nextcloud_client_apt_remove | length > 0
  name: Apt remove {{ nextcloud_client_apt_remove }}
  become: true
  ansible.builtin.apt:
    state: absent
    name: "{{ nextcloud_client_apt_remove }}"